### ISSUE TITLE
Get users with a particular setting?

### ISSUE THREAD

**Issue by haleyngonadi** [zachleigh/laravel-property-bag#21]
Hello,

This is a really awesome. Thanks for sharing. I'm wondering, is it possible to retrieve all users with a particular setting through the user Model? I figure the via setting model below could also work but maybe you have a way more efficient way?

`PropertyBag::where('key', 'music_notifications')->where('value', true)->pluck('owner_id');
`

**Comment by zachleigh** [comment]
Hello!
It is currently not possible to do this, but I think it would be a great addition. I'd happily accept a pull request for this feature, if you or anybody else is up for it. If not, I'll try to get to it sooner than later, but I don't have a lot of time for open source at the moment so don't hold your breath.

Zach
